language: perl
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install:
  # Use latest Augeas
  - sudo add-apt-repository -y ppa:raphink/augeas-dev
  - sudo apt-get update
  - sudo apt-get install libaugeas-dev libtest-pod-perl
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
